### ISSUE TITLE
get rid of ppl_shim

### ISSUE THREAD

**Issue by videlec** [videlec/pplpy#13]
Cython language supports much more now than when the ppl interface was written. Most of `ppl_shim.cc` can be be directly implemented in Cython. See [the documentation](http://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html).
- [x] C++ `delete` statement are `del` in Cython
- [x] increment operator seems to work (see the link above)
- [x] the C++ statement `* my_pointer` is replace in Cython by `my_pointer[0]`
- [x] for C++ dereferencement, use the `dereference` from Cython as defined [here](http://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html#c-operators-not-compatible-with-python-syntax)
- [x]  Poly_Gen_Relation, Poly_Gen_Relation,  MIP_Problem::const_iterator usage (see comment)

**Comment by vinklein** [comment]
Poly_Gen_Relation, Poly_Gen_Relation,  MIP_Problem::const_iterator doesn't have a default constructor. 
Cython generate calls to the default constructor when generating c++ code. Therefore atm we don't have solution to implement new_relation_with and mip_constraints function in Cython 
We need to find a workaround.

**Comment by videlec** [comment]
One possible workaround is to use pointer (ie heap allocated memory). The following works in Cython

    cdef my_cpp_class * A = new my_cpp_class(arg1, arg2 , arg3 , arg4)
    ...
    del A

**Comment by vinklein** [comment]
It works for the mip iterator. But for Poly_Gen_Relation & Poly_Con_Relation the problem is we use relation_with method form Polyhedron class who return Poly_Gen_Relation and Poly_Con_Relation.
Even writing `new PPL_Poly_Con_Relation(self.thisptr[0].relation_with(c.thisptr[0]))` cause a Poly_Con_Relation var to be generate during "cythonization" to stock the relation_with result value.

Looks like this is why these function are ppl_shim in the first place.

**Comment by videlec** [comment]
Ok. Then keep a file ppl_shim but with the minimum number of functions.
